# Generated by Django 6.0.6 on 2026-07-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0002_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('imaging', 'Imaging'), ('vaccination', 'Vaccination'), ('prescription', 'Prescription'), ('medical_history', 'Medical History'), ('allergy', 'Allergy'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_docs/%Y/%m/')),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('has_abnormal', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medisphere.userprofile')),
            ],
            options={
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
    ]
