# Generated by Django 6.0.6 on 2026-07-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0003_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medisphere.familymember'),
        ),
    ]
