# Generated by Django 6.0.6 on 2026-07-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0004_medicaldocument_ai_notes_medicaldocument_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='ai_notes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergy_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergy_medicine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergy_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medisphere.familymember'),
        ),
    ]
