# Generated by Django 6.0.6 on 2026-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0005_remove_medicaldocument_ai_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login_done',
            field=models.BooleanField(default=False),
        ),
    ]
