# Generated by Django 6.0.6 on 2026-07-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0007_medicine_medicineorder_prescriptionorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_home_sample_collection', models.BooleanField(default=False)),
                ('turnaround_hours', models.PositiveIntegerField(blank=True, help_text='Expected result delivery in hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='medisphere.userprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('collection_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('sample_collected', 'Sample Collected'), ('report_ready', 'Report Ready'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_appointments', to='medisphere.userprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_appointments', to='medisphere.userprofile')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medisphere.labtest')),
            ],
            options={
                'ordering': ['-appointment_date', '-created_at'],
            },
        ),
    ]
