# Generated by Django 6.0.6 on 2026-07-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0008_labtest_labappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('lab_confirmed', 'Lab Appointment Confirmed'), ('lab_cancelled', 'Lab Appointment Cancelled'), ('lab_report', 'Lab Report Ready'), ('lab_sample', 'Sample Collected'), ('pharmacy_order', 'Pharmacy Order Update'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='medisphere.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
