# Generated by Django 6.0.6 on 2026-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_image',
            field=models.FileField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
