# Generated by Django 6.0.6 on 2026-07-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisphere', '0011_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
